# docker compose configuration file
# https://docs.docker.com/compose/compose-file/
version: '3.2'
services:
  bot: # name of container alias and lab service
    image: bot # replace with preferred pre-built image name
    build: # remove if using pre-built image
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    environment:
      PORT: '5001'
    volumes:
      - {'type': 'bind', 'source': './cred', 'target': '/opt/cred'}
      - {'type': 'bind', 'source': './data', 'target': '/opt/data'}
      - {'type': 'bind', 'source': './server', 'target': '/opt/server'}
    # command: crond -f
    command: gunicorn -k gevent -w 1 --chdir /opt/server launch:flask_app -b 0.0.0.0:5001 # eg.
    networks: # select from 'none', 'host', 'bridge' and '<custom network>'
      - host
    